In [1]:
%matplotlib inline

# plotting
import matplotlib as mpl
mpl.style.use('ggplot')
import matplotlib.pyplot as plt

# math and data manipulation
import numpy as np
import pandas as pd

# to handle paths
from pathlib import Path

# set random seeds 
import random
from tensorflow import set_random_seed

RANDOM_SEED = 2018
random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)
set_random_seed(RANDOM_SEED)

In [2]:
import warnings
warnings.filterwarnings('ignore')

## Load Files

Load Training data

In [3]:
consumption_train = pd.read_csv('consumption_train.csv', index_col=0, parse_dates=['timestamp'])
consumption_train.head()

series_id           timestamp    consumption  temperature
0     103088 2014-12-24 00:00:00  101842.233424          NaN
1     103088 2014-12-24 01:00:00  105878.048906          NaN
2     103088 2014-12-24 02:00:00   91619.105008          NaN
3     103088 2014-12-24 03:00:00   94473.706203          NaN
4     103088 2014-12-24 04:00:00   96976.755526          NaN

In [4]:
consumption_train.describe()

series_id   consumption    temperature
count  509376.000000  5.093760e+05  280687.000000
mean   101851.234828  1.076238e+05      15.188679
std      1020.487674  1.626611e+05       8.987142
min    100003.000000  0.000000e+00     -13.466667
25%    100998.000000  1.542092e+04       8.451190
50%    101884.500000  4.986205e+04      15.163333
75%    102697.000000  1.351661e+05      21.800000
max    103634.000000  2.085109e+06      44.350000

In [5]:
consumption_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 509376 entries, 0 to 509375
Data columns (total 4 columns):
series_id      509376 non-null int64
timestamp      509376 non-null datetime64[ns]
consumption    509376 non-null float64
temperature    280687 non-null float64
dtypes: datetime64[ns](1), float64(2), int64(1)
memory usage: 19.4 MB


Load Testing data

In [6]:
cold_start_test = pd.read_csv('cold_start_test.csv', index_col=0, parse_dates=['timestamp'])
cold_start_test.head()

series_id           timestamp   consumption  temperature
0     102781 2013-02-27 00:00:00  15295.740389        17.00
1     102781 2013-02-27 01:00:00  15163.209562        18.25
2     102781 2013-02-27 02:00:00  15022.264079        18.00
3     102781 2013-02-27 03:00:00  15370.420458        17.00
4     102781 2013-02-27 04:00:00  15303.103213        16.90

In [7]:
cold_start_test.describe()

series_id   consumption   temperature
count  111984.000000  1.119840e+05  67068.000000
mean   101881.195456  1.585893e+05     15.981019
std      1095.489531  5.282630e+05      7.796996
min    100004.000000  0.000000e+00    -12.212500
25%    100876.000000  1.417107e+04     10.750000
50%    101939.500000  3.869147e+04     16.000000
75%    102920.000000  1.067592e+05     21.600000
max    103629.000000  5.366167e+06     42.000000

In [8]:
cold_start_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 111984 entries, 0 to 111983
Data columns (total 4 columns):
series_id      111984 non-null int64
timestamp      111984 non-null datetime64[ns]
consumption    111984 non-null float64
temperature    67068 non-null float64
dtypes: datetime64[ns](1), float64(2), int64(1)
memory usage: 4.3 MB


Loading Submission data

In [9]:
submission_format = pd.read_csv('submission_format.csv', index_col='pred_id', parse_dates=['timestamp'])
submission_format.head()

series_id  timestamp  temperature  consumption prediction_window
pred_id                                                                  
0           102781 2013-03-03    19.931250          0.0             daily
1           102781 2013-03-04    20.034375          0.0             daily
2           102781 2013-03-05    19.189583          0.0             daily
3           102781 2013-03-06    18.397917          0.0             daily
4           102781 2013-03-07    20.762500          0.0             daily

In [10]:
submission_format.describe()

series_id  temperature  consumption
count    7529.000000  4579.000000       7529.0
mean   101878.964670    16.720556          0.0
std      1070.515261     7.613953          0.0
min    100004.000000    -9.000000          0.0
25%    100882.000000    11.512500          0.0
50%    101947.000000    16.645833          0.0
75%    102890.000000    22.000000          0.0
max    103629.000000    38.727273          0.0

In [11]:
submission_format.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7529 entries, 0 to 7528
Data columns (total 5 columns):
series_id            7529 non-null int64
timestamp            7529 non-null datetime64[ns]
temperature          4579 non-null float64
consumption          7529 non-null float64
prediction_window    7529 non-null object
dtypes: datetime64[ns](1), float64(2), int64(1), object(1)
memory usage: 352.9+ KB


## Training Data

In [12]:
def describe_training_data(train_df):
    num_training_series = train_df.series_id.nunique()
    num_training_days = num_training_series * 28
    num_training_hours = num_training_days * 24
    assert num_training_hours == train_df.shape[0]
    
    desc = f'There are {num_training_series} training ' \
           f'series totaling {num_training_days} days ' \
           f'({num_training_hours} hours) of consumption data.'
    
    print(desc)
    
describe_training_data(consumption_train)

There are 758 training series totaling 21224 days (509376 hours) of consumption data.


#### choose subset of series for training

In [13]:
FRAC_TO_USE = 0.05

rng = np.random.RandomState(seed=RANDOM_SEED)
series_ids = consumption_train.series_id.unique()
training_and_validation_ids = np.random.choice(series_ids, size=int(len(series_ids)*FRAC_TO_USE), replace=False)

# reduce training data to series subset
training_and_validation_data = consumption_train[consumption_train.series_id.isin(training_and_validation_ids)]

# describe the reduced set
describe_training_data(training_and_validation_data)

There are 37 training series totaling 1036 days (24864 hours) of consumption data.


In [14]:
training_and_validation_data.head()

series_id           timestamp    consumption  temperature
21504     103432 2015-08-26 00:00:00  138194.079984          NaN
21505     103432 2015-08-26 01:00:00  123089.088496          NaN
21506     103432 2015-08-26 02:00:00  123193.557517          NaN
21507     103432 2015-08-26 03:00:00  129756.670174          NaN
21508     103432 2015-08-26 04:00:00  127040.475610          NaN

#### split into training and validation

In [15]:
TRAIN_VALID_SPLIT = 0.2

-------------------------------------------- 1 validation set -------------------------------------------------

https://stackoverflow.com/questions/50491630/randomly-split-a-numpy-array

In [16]:
validation_ids = np.random.choice(training_and_validation_ids, int(len(training_and_validation_ids)*TRAIN_VALID_SPLIT), replace=False)
training_ids = list(set(training_and_validation_ids) - set(validation_ids))

training_data = training_and_validation_data[training_and_validation_data.series_id.isin(training_ids)]
validation_data = training_and_validation_data[training_and_validation_data.series_id.isin(validation_ids)]

In [17]:
describe_training_data(training_data)
describe_training_data(validation_data)

There are 30 training series totaling 840 days (20160 hours) of consumption data.
There are 7 training series totaling 196 days (4704 hours) of consumption data.


In [18]:
#TESTING
print(len(training_data.groupby('series_id').count()))
print(len(validation_data.groupby('series_id').count()))

30
7


--------------------------------------------------fin---------------------------------------------------------

#### KFold cross validation

In [19]:
training_and_validation_ids

array([103595, 103370, 102101, 101558, 100685, 102687, 103437, 100450,
       100807, 100142, 101591, 102345, 101075, 100399, 101967, 101926,
       102993, 102640, 100244, 100665, 100139, 103432, 101763, 103298,
       101660, 102162, 103159, 100040, 100425, 102478, 101523, 101203,
       100801, 102997, 101183, 103105, 102892], dtype=int64)

In [20]:
k = int(1/TRAIN_VALID_SPLIT)
k

5

In [21]:
cv_ids = []
from sklearn.model_selection import KFold
kf = KFold(n_splits=k, random_state=RANDOM_SEED)
for train_ids, valid_ids in kf.split(training_and_validation_ids):
    cv_ids.append((training_and_validation_ids[train_ids],training_and_validation_ids[valid_ids]))

## Preprocessing Data

In [22]:
from sklearn.preprocessing import MinMaxScaler

In [23]:
def create_lagged_features(df, lag=1):
    if not type(df) == pd.DataFrame:
        df = pd.DataFrame(df, columns=['consumption'])
    
    def _rename_lag(ser, j):
        ser.name = ser.name + f'_{j}'
        return ser
    
    old_columns = df.columns
        
    # add a column lagged by `i` steps
    for i in range(1, lag + 1):
        df = df.join(df.consumption.shift(i).pipe(_rename_lag, i))
    
    added_features = list( set(df.columns) - set(old_columns))
    
    return df, added_features

In [24]:
def prepare_data(df, feature_generator):

    # scale training data
    consumption_scaler = MinMaxScaler(feature_range=(-1, 1))
    df['consumption'] = consumption_scaler.fit_transform(df['consumption'].values.reshape(-1, 1))

    # convert consumption series to lagged features
    df_extended, added_features = feature_generator(df)
    #TESTING
    #print(df_extended.head())
    #print(added_features)
    
    #handle missing values
    df_extended = df_extended.loc[ df_extended[added_features].dropna().index ]
    #print(df_extended.info()) #TESTING

    # X, y format taking the first column (original time series) to be the y
    X = df_extended[added_features].values
    y = df_extended.consumption
    
    # keras expects 3 dimensional X
    X = X.reshape(X.shape[0], 1, X.shape[1])
    
    return X, y, consumption_scaler

In [25]:
#TESTING
X, y, consumption_scaler = prepare_data(training_data[training_data.series_id == training_data.iloc[0]['series_id']], lambda x: create_lagged_features(x,lag=24))

## Training 

In [26]:
# progress bar
from tqdm import tqdm

https://github.com/tqdm/tqdm/issues/285

In [27]:
def train_model(model, training_data, epochs=3, batch_size=1, desc="Learning Consumption Trends", lag=24):
    for i in tqdm(range(num_passes_through_data), 
                  total=num_passes_through_data, 
                  desc=desc):

        # reset the LSTM state for training on each series
        for ser_id, ser_data in training_data.groupby('series_id'):

            # prepare the data
            X, y, consumption_scaler = prepare_data(ser_data, lambda x: create_lagged_features(x,lag=lag))

            # fit the model: note that we don't shuffle batches (it would ruin the sequence)
            # and that we reset states only after an entire X has been fit, instead of after
            # each (size 1) batch, as is the case when stateful=False

            model.fit(X, y, epochs=1, batch_size=batch_size, verbose=0, shuffle=False)
            model.reset_states()

## Forecasting

### Training data to cold start data

In [28]:
def train_series_to_cold_start(series_df, cold_start_days, prediction_window, window_to_num_preds=None, no_timestamp=['daily','weekly']):
    if window_to_num_preds is None:
        window_to_num_preds = {'hourly':np.arange(24),
                              'daily':np.repeat(np.arange(7),24),
                              'weekly':np.repeat(np.arange(2),24*7)}
    lengths={}
    for k,v in window_to_num_preds.items():
        lengths[k] = len(v) 
    
    cold_start_df = series_df.iloc[:cold_start_days*24]
    
    prediction_df = series_df.iloc[cold_start_days*24:]
    prediction_df['groups'] = pd.Series(window_to_num_preds[prediction_window], index=prediction_df.index[:lengths[prediction_window]])
    prediction_df = prediction_df.groupby('groups').agg({'series_id':'first','timestamp':'last','temperature':'mean','consumption':'sum'})
    
    if prediction_window in no_timestamp:
        prediction_df['timestamp'] = prediction_df['timestamp'].apply(pd.Timestamp.floor, args=('D'))
    
    prediction_df['prediction_window'] = prediction_window
    
    return cold_start_df,prediction_df

In [29]:
def get_cold_start_and_prediction_data(validation_data, prediction_window, cold_start_days=14):
    shuffled_ids = validation_data['series_id'].unique()
    np.random.shuffle(shuffled_ids)
    cold_start_data = pd.DataFrame()
    prediction_data = pd.DataFrame()
    for i in shuffled_ids:
        cold_start_df,prediction_df = train_series_to_cold_start(validation_data[validation_data.series_id==i],cold_start_days,prediction_window)
        cold_start_data = cold_start_data.append(cold_start_df)
        prediction_data = prediction_data.append(prediction_df)

    prediction_data.index = np.arange(len(prediction_data))
    
    return cold_start_data, prediction_data

## Error Metric 

In [30]:
def calc_nmae(y_df,preds_df): 
    w = {'hourly': 24/24,
        'daily':24/7,
        'weekly':24/2}
    
    preds_df['w'] = preds_df.prediction_window.map(w)
    mean_series = y_df.groupby('series_id').consumption.mean().rename('m')
    preds_df = preds_df.join(mean_series,on='series_id')
    preds_df['c'] = preds_df.w/preds_df.m
    
    nmae = (np.abs(y_df.consumption-preds_df.consumption)*preds_df.c).sum()/len(preds_df)
    return nmae

# Base Model

In [31]:
# modeling
import keras
from keras.models import Sequential
from keras.layers import LSTM, Dense

Using TensorFlow backend.


In [59]:
# lag of 24 to simulate smallest cold start window. Our series
# will be converted to a num_timesteps x lag size matrix

def get_base_model(num_neurons=24,lag=24):
    batch_size = 1  # this forces the lstm to step through each time-step one at a time
    batch_input_shape=(batch_size, None, lag)

    # instantiate a sequential model
    model = Sequential()

    # add LSTM layer - stateful MUST be true here in 
    # order to learn the patterns within a series
    model.add(LSTM(units=num_neurons, 
                  batch_input_shape=batch_input_shape, 
                  stateful=True))

    # followed by a dense layer with a single output for regression
    model.add(Dense(1))

    # compile
    model.compile(loss='mean_absolute_error', optimizer='adam')
    
    return model

In [63]:
def generate_hourly_forecast(num_pred_hours, consumption, model, scaler, lag):
    """ Uses last hour's prediction to generate next for num_pred_hours, 
        initialized by most recent cold start prediction. Inverts scale of 
        predictions before return.
    """
    # allocate prediction frame
    preds_scaled = np.zeros(num_pred_hours)
    
    # initial X is last lag values from the cold start
    X = scaler.transform(consumption.values.reshape(-1, 1))[-lag:]
    
    # forecast
    for i in range(num_pred_hours):
        # predict scaled value for next time step
        yhat = model.predict(X.reshape(1, 1, lag), batch_size=1)[0][0]
        preds_scaled[i] = yhat
        
        # update X to be latest data plus prediction
        X = pd.Series(X.ravel()).shift(-1).fillna(yhat).values

    # revert scale back to original range
    hourly_preds = scaler.inverse_transform(preds_scaled.reshape(-1, 1)).ravel()
    return hourly_preds

In [34]:
def get_base_model_predictions(model, cold_start_data, my_predictions, desc="Forecasting from Cold Start Data",lag=24):
    %%time
    pred_window_to_num_preds = {'hourly': 24, 'daily': 7, 'weekly': 2}
    pred_window_to_num_pred_hours = {'hourly': 24, 'daily': 7 * 24, 'weekly': 2 * 7 * 24}

    num_test_series = my_predictions.series_id.nunique()

    model.reset_states()

    for ser_id, pred_df in tqdm(my_predictions.groupby('series_id'), 
                                total=num_test_series, 
                                desc=desc):

        # get info about this series' prediction window
        pred_window = pred_df.prediction_window.unique()[0]
        num_preds = pred_window_to_num_preds[pred_window]
        num_pred_hours = pred_window_to_num_pred_hours[pred_window]

        # prepare cold start data
        series_data = cold_start_data[cold_start_data.series_id == ser_id]
        cold_X, cold_y, consumption_scaler = prepare_data(series_data, lambda x: create_lagged_features(x,lag=24))

        # fine tune our lstm model to this site using cold start data    
        model.fit(cold_X, cold_y, epochs=1, batch_size=1, verbose=0, shuffle=False)

        # make hourly forecasts for duration of pred window
        preds = generate_hourly_forecast(num_pred_hours, series_data.consumption, model, consumption_scaler, lag)

        # reduce by taking sum over each sub window in pred window
        reduced_preds = [pred.sum() for pred in np.split(preds, num_preds)]

        # store result in submission DataFrame
        ser_id_mask = my_predictions.series_id == ser_id
        my_predictions.loc[ser_id_mask, 'consumption'] = reduced_preds
        
    return my_predictions

In [35]:
batch_size=1
lag=24

In [36]:
%%time
num_training_series = training_data.series_id.nunique()
num_passes_through_data = 3
train_cmaes = []
fold_cmaes = []

for fold_num, indices in enumerate(cv_ids):
    train_ids,valid_ids = indices
    training_data = training_and_validation_data[training_and_validation_data.series_id.isin(train_ids)]
    validation_data = training_and_validation_data[training_and_validation_data.series_id.isin(valid_ids)]
    
    model = get_base_model()
    
    #train model
    train_model(model,training_data, desc=f"Learning Consumption Trends - Fold {fold_num}")
    #calculate training error
    train_cold_start_data, train_prediction_data = get_cold_start_and_prediction_data(training_data,'weekly')
    my_train_predictions = train_prediction_data.copy()    
    my_train_predictions = get_base_model_predictions(model, train_cold_start_data, my_train_predictions, desc=f"Forecasting from Training Cold Start Data - Fold {fold_num}")    
    train_cmaes.append(calc_nmae(train_prediction_data,my_train_predictions))
    
    #forecast from validation set and calculate validation error
    cold_start_data, prediction_data = get_cold_start_and_prediction_data(validation_data,'weekly')    
    my_predictions = prediction_data.copy() 
    my_predictions = get_base_model_predictions(model, cold_start_data, my_predictions, desc=f"Forecasting from Cold Start Data - Fold {fold_num}")
    fold_cmaes.append(calc_nmae(prediction_data,my_predictions))

Learning Consumption Trends - Fold 0: 100%|██████████████████████████████████████████████| 3/3 [02:25<00:00, 50.08s/it]


Wall time: 0 ns


Forecasting from Training Cold Start Data - Fold 0: 100%|██████████████████████████████| 29/29 [00:39<00:00,  1.28s/it]


Wall time: 0 ns


Learning Consumption Trends - Fold 1: 100%|██████████████████████████████████████████████| 3/3 [02:09<00:00, 43.95s/it]


Wall time: 0 ns


Forecasting from Training Cold Start Data - Fold 1: 100%|██████████████████████████████| 29/29 [00:41<00:00,  1.61s/it]


Wall time: 996 µs


Learning Consumption Trends - Fold 2: 100%|██████████████████████████████████████████████| 3/3 [02:40<00:00, 55.54s/it]


Wall time: 0 ns


Forecasting from Training Cold Start Data - Fold 2: 100%|██████████████████████████████| 30/30 [00:40<00:00,  1.25s/it]


Wall time: 0 ns


Learning Consumption Trends - Fold 3: 100%|██████████████████████████████████████████████| 3/3 [02:28<00:00, 49.38s/it]


Wall time: 0 ns


Forecasting from Training Cold Start Data - Fold 3: 100%|██████████████████████████████| 30/30 [00:57<00:00,  1.89s/it]


Wall time: 0 ns


Learning Consumption Trends - Fold 4: 100%|██████████████████████████████████████████████| 3/3 [03:21<00:00, 68.09s/it]


Wall time: 0 ns


Forecasting from Training Cold Start Data - Fold 4: 100%|██████████████████████████████| 30/30 [00:54<00:00,  1.65s/it]


Wall time: 0 ns


Forecasting from Cold Start Data - Fold 4: 100%|█████████████████████████████████████████| 7/7 [00:10<00:00,  1.42s/it]


Wall time: 18min 31s


In [60]:
print(sum(train_cmaes)/len(train_cmaes))

3.97037322399


In [61]:
print(sum(fold_cmaes)/len(fold_cmaes))

4.20712859748


In [ ]:
%%time
num_training_series = training_data.series_id.nunique()
num_passes_through_data = 3
train_cmaes_1day = []
fold_cmaes_1day = []

for fold_num, indices in enumerate(cv_ids):
    train_ids,valid_ids = indices
    training_data = training_and_validation_data[training_and_validation_data.series_id.isin(train_ids)]
    validation_data = training_and_validation_data[training_and_validation_data.series_id.isin(valid_ids)]
    
    model = get_base_model()
    
    #train model
    train_model(model,training_data, desc=f"Learning Consumption Trends - Fold {fold_num}")
    #calculate training error
    train_cold_start_data, train_prediction_data = get_cold_start_and_prediction_data(training_data,'daily')
    my_train_predictions = train_prediction_data.copy()    
    my_train_predictions = get_base_model_predictions(model, train_cold_start_data, my_train_predictions, desc=f"Forecasting from Training Cold Start Data - Fold {fold_num}")    
    train_cmaes_1day.append(calc_nmae(train_prediction_data,my_train_predictions))
    
    #forecast from validation set and calculate validation error
    cold_start_data, prediction_data = get_cold_start_and_prediction_data(validation_data,'daily')    
    my_predictions = prediction_data.copy() 
    my_predictions = get_base_model_predictions(model, cold_start_data, my_predictions, desc=f"Forecasting from Cold Start Data - Fold {fold_num}")
    fold_cmaes_1day.append(calc_nmae(prediction_data,my_predictions))

In [ ]:
print(sum(train_cmaes_1day)/len(train_cmaes_1day))

In [ ]:
print(sum(fold_cmaes_1day)/len(fold_cmaes_1day))

In [62]:
%%time
num_training_series = training_data.series_id.nunique()
num_passes_through_data = 3


for fold_num, indices in enumerate(cv_ids):
    train_ids,valid_ids = indices
    training_data = training_and_validation_data[training_and_validation_data.series_id.isin(train_ids)]
    validation_data = training_and_validation_data[training_and_validation_data.series_id.isin(valid_ids)]
    
    model = get_base_model()
    
    #train model
    train_model(model,training_data, desc=f"Learning Consumption Trends - Fold {fold_num}")
    #calculate training error
    train_cold_start_data, train_prediction_data = get_cold_start_and_prediction_data(training_data,'weekly')
    my_train_predictions = train_prediction_data.copy()    
    my_train_predictions = get_base_model_predictions(model, train_cold_start_data, my_train_predictions, desc=f"Forecasting from Training Cold Start Data - Fold {fold_num}")    

    
    #forecast from validation set and calculate validation error
    cold_start_data, prediction_data = get_cold_start_and_prediction_data(validation_data,'weekly')    
    my_predictions = prediction_data.copy() 
    my_predictions = get_base_model_predictions(model, cold_start_data, my_predictions, desc=f"Forecasting from Cold Start Data - Fold {fold_num}")

    break
    

Learning Consumption Trends - Fold 0: 100%|██████████████████████████████████████████████| 3/3 [02:18<00:00, 47.22s/it]


Wall time: 0 ns


Forecasting from Training Cold Start Data - Fold 0:   0%|                                       | 0/29 [00:00<?, ?it/s]

[[-1.19988308]
 [-1.1998831 ]
 [-1.19988306]
 [-1.19988307]
 [-1.19988305]
 [-1.19988302]
 [-1.19988302]
 [-1.19988312]
 [-1.19988305]
 [-1.19988303]
 [-1.19988305]
 [-1.199883  ]
 [-1.19988302]
 [-1.19988303]
 [-1.199883  ]
 [-1.19988298]
 [-1.19988309]
 [-1.19988308]
 [-1.19988299]
 [-1.19988301]
 [-1.19988306]
 [-1.19988309]
 [-1.19988306]
 [-1.19988308]]


Forecasting from Training Cold Start Data - Fold 0:   3%|█                              | 1/29 [00:01<00:48,  1.72s/it]

[[-2.35715591]
 [-2.357157  ]
 [-2.357157  ]
 [-2.357157  ]
 [-2.357157  ]
 [-2.35715591]
 [-2.35715265]
 [-2.35714612]
 [-2.35713851]
 [-2.35713415]
 [-2.35713524]
 [-2.35713307]
 [-2.35713415]
 [-2.35713415]
 [-2.35713198]
 [-2.35713415]
 [-2.35713415]
 [-2.35713415]
 [-2.35713742]
 [-2.35714177]
 [-2.35714286]
 [-2.35714286]
 [-2.35714938]
 [-2.357157  ]]


Forecasting from Training Cold Start Data - Fold 0:   7%|██▏                            | 2/29 [00:03<00:43,  1.61s/it]

[[-1.05942275]
 [-1.05943188]
 [-1.05942883]
 [-1.05943188]
 [-1.05919462]
 [-1.05862277]
 [-1.05850415]
 [-1.05844027]
 [-1.05838856]
 [-1.05842202]
 [-1.0583551 ]
 [-1.05848894]
 [-1.05841898]
 [-1.05857107]
 [-1.05841898]
 [-1.05847981]
 [-1.05859844]
 [-1.05892391]
 [-1.05930717]
 [-1.05931325]
 [-1.059441  ]
 [-1.05943492]
 [-1.05944404]
 [-1.05942275]]


Forecasting from Training Cold Start Data - Fold 0:  10%|███▏                           | 3/29 [00:04<00:39,  1.53s/it]

[[-2.05806926]
 [-2.05806933]
 [-2.05807001]
 [-2.0580696 ]
 [-2.05806877]
 [-2.05806867]
 [-2.05806888]
 [-2.0580689 ]
 [-2.05806814]
 [-2.05806725]
 [-2.05806753]
 [-2.0580672 ]
 [-2.0580672 ]
 [-2.05806698]
 [-2.05806693]
 [-2.0580672 ]
 [-2.05806694]
 [-2.05806691]
 [-2.05806688]
 [-2.05806805]
 [-2.05806784]
 [-2.05806749]
 [-2.05806799]
 [-2.05806859]]


Forecasting from Training Cold Start Data - Fold 0:  14%|████▎                          | 4/29 [00:05<00:37,  1.49s/it]

[[-1.26955421]
 [-1.26955436]
 [-1.26955446]
 [-1.26955471]
 [-1.26955467]
 [-1.26955439]
 [-1.26955447]
 [-1.2695545 ]
 [-1.269512  ]
 [-1.26949969]
 [-1.26949913]
 [-1.26949901]
 [-1.26949915]
 [-1.26949928]
 [-1.26949947]
 [-1.26949905]
 [-1.26949923]
 [-1.26949894]
 [-1.26949965]
 [-1.26949966]
 [-1.26950306]
 [-1.26955826]
 [-1.26955842]
 [-1.26955858]]


Forecasting from Training Cold Start Data - Fold 0:  17%|█████▎                         | 5/29 [00:07<00:35,  1.46s/it]

[[-1.12028018]
 [-1.12028324]
 [-1.12028393]
 [-1.12028401]
 [-1.12028412]
 [-1.12028453]
 [-1.12028431]
 [-1.1202842 ]
 [-1.12028382]
 [-1.12023328]
 [-1.12023673]
 [-1.12025006]
 [-1.12024508]
 [-1.12025082]
 [-1.12025478]
 [-1.12023782]
 [-1.1202491 ]
 [-1.12025006]
 [-1.12023722]
 [-1.12023913]
 [-1.12022867]
 [-1.12026584]
 [-1.12027863]
 [-1.12027778]]


Forecasting from Training Cold Start Data - Fold 0:  21%|██████▍                        | 6/29 [00:08<00:33,  1.44s/it]

[[-1.38835596]
 [-1.38835842]
 [-1.38835838]
 [-1.38835838]
 [-1.38835999]
 [-1.38835872]
 [-1.38835804]
 [-1.38829892]
 [-1.38826205]
 [-1.38822142]
 [-1.38821368]
 [-1.38820505]
 [-1.38819826]
 [-1.38821733]
 [-1.38821113]
 [-1.38819877]
 [-1.38819095]
 [-1.38818165]
 [-1.38819134]
 [-1.3881915 ]
 [-1.3883154 ]
 [-1.38834232]
 [-1.38834118]
 [-1.38834118]]


Forecasting from Training Cold Start Data - Fold 0:  24%|███████▍                       | 7/29 [00:10<00:34,  1.56s/it]

[[-1.21396729]
 [-1.21396778]
 [-1.21396833]
 [-1.21396865]
 [-1.21396826]
 [-1.21396907]
 [-1.21396771]
 [-1.21396852]
 [-1.21396726]
 [-1.21388876]
 [-1.21387289]
 [-1.21387695]
 [-1.21387665]
 [-1.2138785 ]
 [-1.2138785 ]
 [-1.21387188]
 [-1.21388172]
 [-1.21387802]
 [-1.21392983]
 [-1.21397274]
 [-1.21397106]
 [-1.21397089]
 [-1.21397161]
 [-1.21397044]]


Forecasting from Training Cold Start Data - Fold 0:  28%|████████▌                      | 8/29 [00:12<00:36,  1.74s/it]

[[-1.36002565]
 [-1.35998651]
 [-1.35995749]
 [-1.35998456]
 [-1.35995846]
 [-1.35999236]
 [-1.35996409]
 [-1.35985363]
 [-1.35986165]
 [-1.35989697]
 [-1.3598993 ]
 [-1.35984943]
 [-1.35987058]
 [-1.35982701]
 [-1.35984111]
 [-1.35988475]
 [-1.35985581]
 [-1.35983203]
 [-1.35987283]
 [-1.35988378]
 [-1.35990117]
 [-1.35994744]
 [-1.35995381]
 [-1.35999303]]


Forecasting from Training Cold Start Data - Fold 0:  31%|█████████▌                     | 9/29 [00:13<00:32,  1.64s/it]

[[-1.03943932]
 [-1.03943942]
 [-1.03943913]
 [-1.03943917]
 [-1.03943916]
 [-1.0394391 ]
 [-1.0394404 ]
 [-1.03944088]
 [-1.03944186]
 [-1.03943899]
 [-1.03943854]
 [-1.03943813]
 [-1.03943992]
 [-1.0394407 ]
 [-1.03943939]
 [-1.03943864]
 [-1.03943689]
 [-1.03943755]
 [-1.03943899]
 [-1.03943964]
 [-1.03943983]
 [-1.0394429 ]
 [-1.03944307]
 [-1.03944305]]


Forecasting from Training Cold Start Data - Fold 0:  34%|██████████▎                   | 10/29 [00:16<00:33,  1.77s/it]

[[-2.20856227]
 [-2.20856227]
 [-2.20766098]
 [-2.20856227]
 [-2.20856227]
 [-2.20856227]
 [-2.20766098]
 [-2.20766098]
 [-2.20856227]
 [-2.20856227]
 [-2.20856227]
 [-2.19053644]
 [-2.18963515]
 [-2.18963515]
 [-2.18963515]
 [-2.18873386]
 [-2.18873386]
 [-2.18963515]
 [-2.18963515]
 [-2.18963515]
 [-2.18963515]
 [-2.18963515]
 [-2.18873386]
 [-2.18873386]]


Forecasting from Training Cold Start Data - Fold 0:  38%|███████████▍                  | 11/29 [00:17<00:32,  1.79s/it]

[[-1.03841689]
 [-1.03841689]
 [-1.0384169 ]
 [-1.03841689]
 [-1.03841689]
 [-1.0384169 ]
 [-1.0384169 ]
 [-1.03841684]
 [-1.03840148]
 [-1.03840162]
 [-1.03840141]
 [-1.0384026 ]
 [-1.03840278]
 [-1.03840271]
 [-1.03840291]
 [-1.03840311]
 [-1.03840325]
 [-1.03840398]
 [-1.03840326]
 [-1.03840648]
 [-1.03840919]
 [-1.03841354]
 [-1.03841686]
 [-1.03841685]]


Forecasting from Training Cold Start Data - Fold 0:  41%|████████████▍                 | 12/29 [00:19<00:31,  1.85s/it]

[[-2.00737796]
 [-2.00737808]
 [-2.00737862]
 [-2.007378  ]
 [-2.00737776]
 [-2.00737898]
 [-2.00737608]
 [-2.00737389]
 [-2.00737067]
 [-2.00737048]
 [-2.00736684]
 [-2.00736637]
 [-2.00736829]
 [-2.00736868]
 [-2.00736879]
 [-2.00737177]
 [-2.00737071]
 [-2.00736966]
 [-2.0073686 ]
 [-2.00737064]
 [-2.00737064]
 [-2.00737479]
 [-2.00737729]
 [-2.007378  ]]


Forecasting from Training Cold Start Data - Fold 0:  45%|█████████████▍                | 13/29 [00:22<00:31,  1.96s/it]

[[-1.80289371]
 [-1.8028941 ]
 [-1.80289423]
 [-1.80289389]
 [-1.80289409]
 [-1.80289221]
 [-1.80288932]
 [-1.80288885]
 [-1.80288816]
 [-1.80288907]
 [-1.80288916]
 [-1.80288973]
 [-1.80288972]
 [-1.80289015]
 [-1.80289111]
 [-1.80289172]
 [-1.80289253]
 [-1.8028948 ]
 [-1.80289468]
 [-1.80289443]
 [-1.80289527]
 [-1.80289533]
 [-1.80289507]
 [-1.80289583]]


Forecasting from Training Cold Start Data - Fold 0:  48%|██████████████▍               | 14/29 [00:24<00:29,  1.95s/it]

[[-3.12063111]
 [-3.12062549]
 [-3.12062833]
 [-3.12062289]
 [-3.12062488]
 [-3.12062494]
 [-3.1206283 ]
 [-3.12062264]
 [-3.12062882]
 [-3.12062858]
 [-3.12062532]
 [-3.12062434]
 [-3.12061989]
 [-3.12062156]
 [-3.12061979]
 [-3.1206179 ]
 [-3.12062091]
 [-3.12061716]
 [-3.12061939]
 [-3.12061438]
 [-3.12061307]
 [-3.12062061]
 [-3.12062785]
 [-3.12062766]]


Forecasting from Training Cold Start Data - Fold 0:  52%|███████████████▌              | 15/29 [00:25<00:26,  1.92s/it]

[[-1.04581949]
 [-1.04581949]
 [-1.04581949]
 [-1.04581949]
 [-1.04581949]
 [-1.04581959]
 [-1.04577747]
 [-1.04577747]
 [-1.04577584]
 [-1.04563305]
 [-1.04577574]
 [-1.04577502]
 [-1.04577543]
 [-1.04577492]
 [-1.04577635]
 [-1.04577574]
 [-1.04577645]
 [-1.04575809]
 [-1.04576778]
 [-1.04577523]
 [-1.04577614]
 [-1.04577584]
 [-1.04582031]
 [-1.0458202 ]]


Forecasting from Training Cold Start Data - Fold 0:  55%|████████████████▌             | 16/29 [00:27<00:25,  1.95s/it]

[[-1.15674867]
 [-1.15674867]
 [-1.15674864]
 [-1.15674888]
 [-1.15674887]
 [-1.15674887]
 [-1.15674889]
 [-1.15674885]
 [-1.15674135]
 [-1.15673297]
 [-1.1567326 ]
 [-1.15673326]
 [-1.15673229]
 [-1.15673272]
 [-1.15673311]
 [-1.15673267]
 [-1.15673276]
 [-1.15673243]
 [-1.15673271]
 [-1.15673321]
 [-1.15672685]
 [-1.15674767]
 [-1.15674769]
 [-1.15674768]]


Forecasting from Training Cold Start Data - Fold 0:  59%|█████████████████▌            | 17/29 [00:29<00:22,  1.91s/it]

[[-1.41362812]
 [-1.4136283 ]
 [-1.41362875]
 [-1.41362838]
 [-1.41362855]
 [-1.41357232]
 [-1.41355483]
 [-1.41355735]
 [-1.4135454 ]
 [-1.41353021]
 [-1.41352612]
 [-1.41352584]
 [-1.41352821]
 [-1.41353473]
 [-1.41353378]
 [-1.41353207]
 [-1.41352316]
 [-1.41352327]
 [-1.41353438]
 [-1.41354416]
 [-1.41354674]
 [-1.41355104]
 [-1.41357127]
 [-1.41357985]]


Forecasting from Training Cold Start Data - Fold 0:  62%|██████████████████▌           | 18/29 [00:31<00:21,  1.98s/it]

[[-1.13792561]
 [-1.13792562]
 [-1.13792524]
 [-1.1379257 ]
 [-1.13792583]
 [-1.13792588]
 [-1.13792547]
 [-1.13792536]
 [-1.13787474]
 [-1.13786127]
 [-1.13786593]
 [-1.13786767]
 [-1.13786685]
 [-1.13786748]
 [-1.13786764]
 [-1.13786743]
 [-1.13786715]
 [-1.13786231]
 [-1.13786265]
 [-1.13786294]
 [-1.1378684 ]
 [-1.1379257 ]
 [-1.13792552]
 [-1.13792535]]


Forecasting from Training Cold Start Data - Fold 0:  66%|███████████████████▋          | 19/29 [00:33<00:19,  1.96s/it]

[[-2.36669384]
 [-2.36669546]
 [-2.3666965 ]
 [-2.36669569]
 [-2.36669446]
 [-2.36669439]
 [-2.36667804]
 [-2.36667637]
 [-2.36667613]
 [-2.36667764]
 [-2.36667895]
 [-2.36668807]
 [-2.36669093]
 [-2.36669166]
 [-2.36669293]
 [-2.36669277]
 [-2.36669239]
 [-2.3666948 ]
 [-2.36669493]
 [-2.36669503]
 [-2.36669567]
 [-2.36669385]
 [-2.3666952 ]
 [-2.36669087]]


Forecasting from Training Cold Start Data - Fold 0:  69%|████████████████████▋         | 20/29 [00:35<00:17,  1.93s/it]

[[-1.4679555 ]
 [-1.46794961]
 [-1.46795096]
 [-1.46794926]
 [-1.46794865]
 [-1.46794962]
 [-1.46795474]
 [-1.46790231]
 [-1.46789821]
 [-1.46789191]
 [-1.46788911]
 [-1.46788975]
 [-1.46792767]
 [-1.46794202]
 [-1.46792795]
 [-1.46788816]
 [-1.46788516]
 [-1.46788794]
 [-1.46789668]
 [-1.46790892]
 [-1.46794456]
 [-1.4679451 ]
 [-1.46794696]
 [-1.46795287]]


Forecasting from Training Cold Start Data - Fold 0:  72%|█████████████████████▋        | 21/29 [00:37<00:14,  1.81s/it]

[[-1.2217763 ]
 [-1.2217768 ]
 [-1.22177653]
 [-1.22177685]
 [-1.22177679]
 [-1.22178609]
 [-1.22169108]
 [-1.22173845]
 [-1.22167927]
 [-1.22164376]
 [-1.2216505 ]
 [-1.22165216]
 [-1.2216629 ]
 [-1.22167804]
 [-1.22167888]
 [-1.22166541]
 [-1.22163954]
 [-1.22164064]
 [-1.22164243]
 [-1.2217239 ]
 [-1.2217849 ]
 [-1.22173886]
 [-1.22173982]
 [-1.22174   ]]


Forecasting from Training Cold Start Data - Fold 0:  76%|██████████████████████▊       | 22/29 [00:38<00:11,  1.69s/it]

[[-1.93816902]
 [-1.93816937]
 [-1.93816257]
 [-1.93816604]
 [-1.93816553]
 [-1.93817126]
 [-1.93816389]
 [-1.93815774]
 [-1.93813388]
 [-1.93811891]
 [-1.9381228 ]
 [-1.93812677]
 [-1.93812094]
 [-1.93817464]
 [-1.93816246]
 [-1.93814704]
 [-1.93812389]
 [-1.93811784]
 [-1.93811204]
 [-1.93813763]
 [-1.93816112]
 [-1.9381611 ]
 [-1.93817036]
 [-1.93817198]]


Forecasting from Training Cold Start Data - Fold 0:  79%|███████████████████████▊      | 23/29 [00:40<00:10,  1.69s/it]

[[-1.7103914 ]
 [-1.71039103]
 [-1.71039107]
 [-1.71039088]
 [-1.71039118]
 [-1.71038632]
 [-1.71038453]
 [-1.71038212]
 [-1.71038168]
 [-1.7103788 ]
 [-1.71037761]
 [-1.71038084]
 [-1.71037912]
 [-1.71037918]
 [-1.71038174]
 [-1.71038338]
 [-1.71038427]
 [-1.71038921]
 [-1.71038974]
 [-1.71039057]
 [-1.7103898 ]
 [-1.71038969]
 [-1.71039059]
 [-1.71039102]]


Forecasting from Training Cold Start Data - Fold 0:  83%|████████████████████████▊     | 24/29 [00:41<00:08,  1.68s/it]

[[-2.609905  ]
 [-2.60990896]
 [-2.6099098 ]
 [-2.60990955]
 [-2.60991011]
 [-2.60991258]
 [-2.60991132]
 [-2.60991104]
 [-2.6099103 ]
 [-2.609909  ]
 [-2.60990836]
 [-2.60990864]
 [-2.60990432]
 [-2.609903  ]
 [-2.60990182]
 [-2.60990478]
 [-2.60990155]
 [-2.60989875]
 [-2.60989499]
 [-2.60989863]
 [-2.60990053]
 [-2.60989988]
 [-2.60990428]
 [-2.60990368]]


Forecasting from Training Cold Start Data - Fold 0:  86%|█████████████████████████▊    | 25/29 [00:43<00:06,  1.72s/it]

[[-1.29288829]
 [-1.29288829]
 [-1.29288829]
 [-1.29288829]
 [-1.29288829]
 [-1.29288829]
 [-1.29289867]
 [-1.29242137]
 [-1.29157053]
 [-1.29092721]
 [-1.29101022]
 [-1.29123849]
 [-1.29147714]
 [-1.29104135]
 [-1.29113473]
 [-1.29099984]
 [-1.29171579]
 [-1.29171579]
 [-1.29229685]
 [-1.29204783]
 [-1.29269114]
 [-1.29287791]
 [-1.29287791]
 [-1.29287791]]


Forecasting from Training Cold Start Data - Fold 0:  90%|██████████████████████████▉   | 26/29 [00:45<00:05,  1.86s/it]

[[-1.66529984]
 [-1.66530037]
 [-1.66530211]
 [-1.66530037]
 [-1.66530056]
 [-1.66529423]
 [-1.66528913]
 [-1.6652847 ]
 [-1.66527567]
 [-1.66527988]
 [-1.66528185]
 [-1.66527933]
 [-1.66527905]
 [-1.66527909]
 [-1.66528194]
 [-1.66527936]
 [-1.66527782]
 [-1.6652797 ]
 [-1.66527953]
 [-1.66528185]
 [-1.66528353]
 [-1.66529827]
 [-1.66529908]
 [-1.66530072]]


Forecasting from Training Cold Start Data - Fold 0:  93%|███████████████████████████▉  | 27/29 [00:47<00:03,  1.89s/it]

[[-2.21117648]
 [-2.2111774 ]
 [-2.21117701]
 [-2.21117842]
 [-2.21117697]
 [-2.21117612]
 [-2.21116579]
 [-2.21116358]
 [-2.21116108]
 [-2.21116025]
 [-2.21116424]
 [-2.211165  ]
 [-2.21116141]
 [-2.21116614]
 [-2.21116884]
 [-2.21116994]
 [-2.21116967]
 [-2.21117241]
 [-2.21117393]
 [-2.21117534]
 [-2.21117517]
 [-2.21117488]
 [-2.21117613]
 [-2.21117718]]


Forecasting from Training Cold Start Data - Fold 0:  97%|████████████████████████████▉ | 28/29 [00:49<00:01,  1.83s/it]

[[-2.29441874]
 [-2.29442089]
 [-2.29442104]
 [-2.29442108]
 [-2.29442082]
 [-2.2944219 ]
 [-2.29442277]
 [-2.29442244]
 [-2.294422  ]
 [-2.29442006]
 [-2.29441793]
 [-2.29441554]
 [-2.2944174 ]
 [-2.29441768]
 [-2.29441814]
 [-2.29441935]
 [-2.29441887]
 [-2.29441758]
 [-2.29441755]
 [-2.29441816]
 [-2.29441871]
 [-2.29441797]
 [-2.29441789]
 [-2.2944205 ]]


Forecasting from Training Cold Start Data - Fold 0: 100%|██████████████████████████████| 29/29 [00:51<00:00,  1.92s/it]


Wall time: 0 ns


Forecasting from Cold Start Data - Fold 0:   0%|                                                 | 0/8 [00:00<?, ?it/s]

[[-1.40152568]
 [-1.40152572]
 [-1.40152584]
 [-1.40152593]
 [-1.40152601]
 [-1.40152601]
 [-1.40152601]
 [-1.40152584]
 [-1.40152593]
 [-1.40152601]
 [-1.4015261 ]
 [-1.4015261 ]
 [-1.40152614]
 [-1.40152618]
 [-1.40152618]
 [-1.40152597]
 [-1.40152618]
 [-1.40152601]
 [-1.40152618]
 [-1.40152601]
 [-1.40152584]
 [-1.40152589]
 [-1.40152576]
 [-1.40152584]]


Forecasting from Cold Start Data - Fold 0:  12%|█████▏                                   | 1/8 [00:01<00:13,  1.89s/it]

[[-8.28708586]
 [-8.2870014 ]
 [-8.28715692]
 [-8.28698978]
 [-8.28700051]
 [-8.28704519]
 [-8.28699872]
 [-8.28707737]
 [-8.2870081 ]
 [-8.28703492]
 [-8.28697593]
 [-8.28687135]
 [-8.28684856]
 [-8.28686018]
 [-8.2867355 ]
 [-8.28679404]
 [-8.28670823]
 [-8.28677214]
 [-8.2869214 ]
 [-8.2868937 ]
 [-8.28692275]
 [-8.28708184]
 [-8.28696788]
 [-8.28702508]]


Forecasting from Cold Start Data - Fold 0:  25%|██████████▎                              | 2/8 [00:03<00:11,  1.92s/it]

[[-1.41773214]
 [-1.41773152]
 [-1.41773168]
 [-1.41773216]
 [-1.41773082]
 [-1.41771448]
 [-1.41770801]
 [-1.4177101 ]
 [-1.41770477]
 [-1.41770387]
 [-1.4177073 ]
 [-1.41770934]
 [-1.41771031]
 [-1.41771253]
 [-1.41771266]
 [-1.41771287]
 [-1.41771022]
 [-1.41770492]
 [-1.41770841]
 [-1.41771717]
 [-1.41772077]
 [-1.41773042]
 [-1.41773193]
 [-1.41773231]]


Forecasting from Cold Start Data - Fold 0:  38%|███████████████▍                         | 3/8 [00:05<00:09,  1.81s/it]

[[-1.19289748]
 [-1.19290214]
 [-1.19290262]
 [-1.1928993 ]
 [-1.19287664]
 [-1.19289839]
 [-1.1928993 ]
 [-1.19290262]
 [-1.19287815]
 [-1.19255499]
 [-1.192616  ]
 [-1.19258066]
 [-1.19247707]
 [-1.19257613]
 [-1.19275523]
 [-1.19276399]
 [-1.19263956]
 [-1.19270842]
 [-1.19273258]
 [-1.19279208]
 [-1.19284161]
 [-1.19289748]
 [-1.19290141]
 [-1.1928996 ]]


Forecasting from Cold Start Data - Fold 0:  50%|████████████████████▌                    | 4/8 [00:06<00:06,  1.68s/it]

[[-2.36364787]
 [-2.363645  ]
 [-2.36364787]
 [-2.36364068]
 [-2.36364643]
 [-2.36364068]
 [-2.36364068]
 [-2.36363205]
 [-2.36362773]
 [-2.36362773]
 [-2.36362485]
 [-2.36362629]
 [-2.36362773]
 [-2.36362917]
 [-2.36362629]
 [-2.36362773]
 [-2.36362773]
 [-2.36363492]
 [-2.36363636]
 [-2.36363924]
 [-2.36364068]
 [-2.3636378 ]
 [-2.36363924]
 [-2.36363924]]


Forecasting from Cold Start Data - Fold 0:  62%|█████████████████████████▋               | 5/8 [00:08<00:04,  1.58s/it]

[[-1.45661931]
 [-1.45661979]
 [-1.4566215 ]
 [-1.45662223]
 [-1.45662241]
 [-1.45662258]
 [-1.45662066]
 [-1.45662045]
 [-1.4566187 ]
 [-1.45661791]
 [-1.45661795]
 [-1.45661775]
 [-1.45661859]
 [-1.4566187 ]
 [-1.45661819]
 [-1.45661802]
 [-1.45661842]
 [-1.4566186 ]
 [-1.45661853]
 [-1.45661822]
 [-1.4566176 ]
 [-1.45661772]
 [-1.45661859]
 [-1.45661904]]


Forecasting from Cold Start Data - Fold 0:  75%|██████████████████████████████▊          | 6/8 [00:09<00:03,  1.51s/it]

[[-1.6625403 ]
 [-1.66253996]
 [-1.66253984]
 [-1.66254018]
 [-1.66254046]
 [-1.66254051]
 [-1.66252563]
 [-1.66251873]
 [-1.66251606]
 [-1.66251367]
 [-1.66251913]
 [-1.66252236]
 [-1.66252276]
 [-1.66252412]
 [-1.66252392]
 [-1.66252279]
 [-1.6625223 ]
 [-1.66252015]
 [-1.6625192 ]
 [-1.66251865]
 [-1.66252487]
 [-1.66253747]
 [-1.66253677]
 [-1.66253746]]


Forecasting from Cold Start Data - Fold 0:  88%|███████████████████████████████████▉     | 7/8 [00:10<00:01,  1.47s/it]

[[-1.11793811]
 [-1.11794403]
 [-1.11794382]
 [-1.11794458]
 [-1.11794428]
 [-1.11794445]
 [-1.11794441]
 [-1.11794437]
 [-1.11794093]
 [-1.1179191 ]
 [-1.11792074]
 [-1.1179217 ]
 [-1.11792086]
 [-1.11792145]
 [-1.11791994]
 [-1.11791851]
 [-1.11792015]
 [-1.11788431]
 [-1.11789497]
 [-1.11785232]
 [-1.1178449 ]
 [-1.11792124]
 [-1.11793417]
 [-1.11793396]]


Forecasting from Cold Start Data - Fold 0: 100%|█████████████████████████████████████████| 8/8 [00:12<00:00,  1.43s/it]


Wall time: 3min 30s


In [64]:
calc_nmae(train_prediction_data,my_train_predictions)

4.6096432797222082

In [65]:
calc_nmae(prediction_data,my_predictions)

3.4215315834649154

In [38]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_5 (LSTM)                (1, 24)                   4704      
_________________________________________________________________
dense_5 (Dense)              (1, 1)                    25        
Total params: 4,729
Trainable params: 4,729
Non-trainable params: 0
_________________________________________________________________


In [40]:
cv_ids[0][0]

array([100807, 100142, 101591, 102345, 101075, 100399, 101967, 101926,
       102993, 102640, 100244, 100665, 100139, 103432, 101763, 103298,
       101660, 102162, 103159, 100040, 100425, 102478, 101523, 101203,
       100801, 102997, 101183, 103105, 102892], dtype=int64)

In [41]:
 temp_data = training_and_validation_data[training_and_validation_data.series_id.isin(cv_ids[0][0])]

In [43]:
temp_cold_start_data, temp_prediction_data = get_cold_start_and_prediction_data(temp_data,'weekly')

In [44]:
my_test_predictions = test_prediction_data.copy()

In [47]:
 my_test_predictions = get_base_model_predictions(model, test_cold_start_data, my_test_predictions, desc=f"Forecasting from Training Cold Start Data - Fold {fold_num}")    

Wall time: 0 ns


Forecasting from Training Cold Start Data - Fold 4:   0%|                                       | 0/30 [00:00<?, ?it/s]

[[-1.19988308]
 [-1.1998831 ]
 [-1.19988306]
 [-1.19988307]
 [-1.19988305]
 [-1.19988302]
 [-1.19988302]
 [-1.19988312]
 [-1.19988305]
 [-1.19988303]
 [-1.19988305]
 [-1.199883  ]
 [-1.19988302]
 [-1.19988303]
 [-1.199883  ]
 [-1.19988298]
 [-1.19988309]
 [-1.19988308]
 [-1.19988299]
 [-1.19988301]
 [-1.19988306]
 [-1.19988309]
 [-1.19988306]
 [-1.19988308]]


Forecasting from Training Cold Start Data - Fold 4:   3%|█                              | 1/30 [00:01<00:39,  1.35s/it]

[[-2.35715591]
 [-2.357157  ]
 [-2.357157  ]
 [-2.357157  ]
 [-2.357157  ]
 [-2.35715591]
 [-2.35715265]
 [-2.35714612]
 [-2.35713851]
 [-2.35713415]
 [-2.35713524]
 [-2.35713307]
 [-2.35713415]
 [-2.35713415]
 [-2.35713198]
 [-2.35713415]
 [-2.35713415]
 [-2.35713415]
 [-2.35713742]
 [-2.35714177]
 [-2.35714286]
 [-2.35714286]
 [-2.35714938]
 [-2.357157  ]]


Forecasting from Training Cold Start Data - Fold 4:   7%|██                             | 2/30 [00:02<00:37,  1.35s/it]

[[-1.05942275]
 [-1.05943188]
 [-1.05942883]
 [-1.05943188]
 [-1.05919462]
 [-1.05862277]
 [-1.05850415]
 [-1.05844027]
 [-1.05838856]
 [-1.05842202]
 [-1.0583551 ]
 [-1.05848894]
 [-1.05841898]
 [-1.05857107]
 [-1.05841898]
 [-1.05847981]
 [-1.05859844]
 [-1.05892391]
 [-1.05930717]
 [-1.05931325]
 [-1.059441  ]
 [-1.05943492]
 [-1.05944404]
 [-1.05942275]]


Forecasting from Training Cold Start Data - Fold 4:  10%|███                            | 3/30 [00:04<00:36,  1.35s/it]

[[-2.05806926]
 [-2.05806933]
 [-2.05807001]
 [-2.0580696 ]
 [-2.05806877]
 [-2.05806867]
 [-2.05806888]
 [-2.0580689 ]
 [-2.05806814]
 [-2.05806725]
 [-2.05806753]
 [-2.0580672 ]
 [-2.0580672 ]
 [-2.05806698]
 [-2.05806693]
 [-2.0580672 ]
 [-2.05806694]
 [-2.05806691]
 [-2.05806688]
 [-2.05806805]
 [-2.05806784]
 [-2.05806749]
 [-2.05806799]
 [-2.05806859]]


Forecasting from Training Cold Start Data - Fold 4:  13%|████▏                          | 4/30 [00:06<00:41,  1.59s/it]

[[-1.26955421]
 [-1.26955436]
 [-1.26955446]
 [-1.26955471]
 [-1.26955467]
 [-1.26955439]
 [-1.26955447]
 [-1.2695545 ]
 [-1.269512  ]
 [-1.26949969]
 [-1.26949913]
 [-1.26949901]
 [-1.26949915]
 [-1.26949928]
 [-1.26949947]
 [-1.26949905]
 [-1.26949923]
 [-1.26949894]
 [-1.26949965]
 [-1.26949966]
 [-1.26950306]
 [-1.26955826]
 [-1.26955842]
 [-1.26955858]]


Forecasting from Training Cold Start Data - Fold 4:  17%|█████▏                         | 5/30 [00:07<00:38,  1.55s/it]

[[-1.12028018]
 [-1.12028324]
 [-1.12028393]
 [-1.12028401]
 [-1.12028412]
 [-1.12028453]
 [-1.12028431]
 [-1.1202842 ]
 [-1.12028382]
 [-1.12023328]
 [-1.12023673]
 [-1.12025006]
 [-1.12024508]
 [-1.12025082]
 [-1.12025478]
 [-1.12023782]
 [-1.1202491 ]
 [-1.12025006]
 [-1.12023722]
 [-1.12023913]
 [-1.12022867]
 [-1.12026584]
 [-1.12027863]
 [-1.12027778]]


Forecasting from Training Cold Start Data - Fold 4:  20%|██████▏                        | 6/30 [00:09<00:36,  1.51s/it]

[[-1.40152568]
 [-1.40152572]
 [-1.40152584]
 [-1.40152593]
 [-1.40152601]
 [-1.40152601]
 [-1.40152601]
 [-1.40152584]
 [-1.40152593]
 [-1.40152601]
 [-1.4015261 ]
 [-1.4015261 ]
 [-1.40152614]
 [-1.40152618]
 [-1.40152618]
 [-1.40152597]
 [-1.40152618]
 [-1.40152601]
 [-1.40152618]
 [-1.40152601]
 [-1.40152584]
 [-1.40152589]
 [-1.40152576]
 [-1.40152584]]


Forecasting from Training Cold Start Data - Fold 4:  23%|███████▏                       | 7/30 [00:10<00:34,  1.51s/it]

[[-1.38835596]
 [-1.38835842]
 [-1.38835838]
 [-1.38835838]
 [-1.38835999]
 [-1.38835872]
 [-1.38835804]
 [-1.38829892]
 [-1.38826205]
 [-1.38822142]
 [-1.38821368]
 [-1.38820505]
 [-1.38819826]
 [-1.38821733]
 [-1.38821113]
 [-1.38819877]
 [-1.38819095]
 [-1.38818165]
 [-1.38819134]
 [-1.3881915 ]
 [-1.3883154 ]
 [-1.38834232]
 [-1.38834118]
 [-1.38834118]]


Forecasting from Training Cold Start Data - Fold 4:  27%|████████▎                      | 8/30 [00:11<00:31,  1.45s/it]

[[-8.28708586]
 [-8.2870014 ]
 [-8.28715692]
 [-8.28698978]
 [-8.28700051]
 [-8.28704519]
 [-8.28699872]
 [-8.28707737]
 [-8.2870081 ]
 [-8.28703492]
 [-8.28697593]
 [-8.28687135]
 [-8.28684856]
 [-8.28686018]
 [-8.2867355 ]
 [-8.28679404]
 [-8.28670823]
 [-8.28677214]
 [-8.2869214 ]
 [-8.2868937 ]
 [-8.28692275]
 [-8.28708184]
 [-8.28696788]
 [-8.28702508]]


Forecasting from Training Cold Start Data - Fold 4:  30%|█████████▎                     | 9/30 [00:13<00:32,  1.57s/it]

[[-1.36002565]
 [-1.35998651]
 [-1.35995749]
 [-1.35998456]
 [-1.35995846]
 [-1.35999236]
 [-1.35996409]
 [-1.35985363]
 [-1.35986165]
 [-1.35989697]
 [-1.3598993 ]
 [-1.35984943]
 [-1.35987058]
 [-1.35982701]
 [-1.35984111]
 [-1.35988475]
 [-1.35985581]
 [-1.35983203]
 [-1.35987283]
 [-1.35988378]
 [-1.35990117]
 [-1.35994744]
 [-1.35995381]
 [-1.35999303]]


Forecasting from Training Cold Start Data - Fold 4:  33%|██████████                    | 10/30 [00:15<00:31,  1.60s/it]

[[-1.03943932]
 [-1.03943942]
 [-1.03943913]
 [-1.03943917]
 [-1.03943916]
 [-1.0394391 ]
 [-1.0394404 ]
 [-1.03944088]
 [-1.03944186]
 [-1.03943899]
 [-1.03943854]
 [-1.03943813]
 [-1.03943992]
 [-1.0394407 ]
 [-1.03943939]
 [-1.03943864]
 [-1.03943689]
 [-1.03943755]
 [-1.03943899]
 [-1.03943964]
 [-1.03943983]
 [-1.0394429 ]
 [-1.03944307]
 [-1.03944305]]


Forecasting from Training Cold Start Data - Fold 4:  37%|███████████                   | 11/30 [00:16<00:28,  1.51s/it]

[[-1.41773214]
 [-1.41773152]
 [-1.41773168]
 [-1.41773216]
 [-1.41773082]
 [-1.41771448]
 [-1.41770801]
 [-1.4177101 ]
 [-1.41770477]
 [-1.41770387]
 [-1.4177073 ]
 [-1.41770934]
 [-1.41771031]
 [-1.41771253]
 [-1.41771266]
 [-1.41771287]
 [-1.41771022]
 [-1.41770492]
 [-1.41770841]
 [-1.41771717]
 [-1.41772077]
 [-1.41773042]
 [-1.41773193]
 [-1.41773231]]


Forecasting from Training Cold Start Data - Fold 4:  40%|████████████                  | 12/30 [00:18<00:26,  1.48s/it]

[[-1.80289371]
 [-1.8028941 ]
 [-1.80289423]
 [-1.80289389]
 [-1.80289409]
 [-1.80289221]
 [-1.80288932]
 [-1.80288885]
 [-1.80288816]
 [-1.80288907]
 [-1.80288916]
 [-1.80288973]
 [-1.80288972]
 [-1.80289015]
 [-1.80289111]
 [-1.80289172]
 [-1.80289253]
 [-1.8028948 ]
 [-1.80289468]
 [-1.80289443]
 [-1.80289527]
 [-1.80289533]
 [-1.80289507]
 [-1.80289583]]


Forecasting from Training Cold Start Data - Fold 4:  43%|█████████████                 | 13/30 [00:19<00:24,  1.45s/it]

[[-3.12063111]
 [-3.12062549]
 [-3.12062833]
 [-3.12062289]
 [-3.12062488]
 [-3.12062494]
 [-3.1206283 ]
 [-3.12062264]
 [-3.12062882]
 [-3.12062858]
 [-3.12062532]
 [-3.12062434]
 [-3.12061989]
 [-3.12062156]
 [-3.12061979]
 [-3.1206179 ]
 [-3.12062091]
 [-3.12061716]
 [-3.12061939]
 [-3.12061438]
 [-3.12061307]
 [-3.12062061]
 [-3.12062785]
 [-3.12062766]]


Forecasting from Training Cold Start Data - Fold 4:  47%|██████████████                | 14/30 [00:20<00:22,  1.43s/it]

[[-1.04581949]
 [-1.04581949]
 [-1.04581949]
 [-1.04581949]
 [-1.04581949]
 [-1.04581959]
 [-1.04577747]
 [-1.04577747]
 [-1.04577584]
 [-1.04563305]
 [-1.04577574]
 [-1.04577502]
 [-1.04577543]
 [-1.04577492]
 [-1.04577635]
 [-1.04577574]
 [-1.04577645]
 [-1.04575809]
 [-1.04576778]
 [-1.04577523]
 [-1.04577614]
 [-1.04577584]
 [-1.04582031]
 [-1.0458202 ]]


Forecasting from Training Cold Start Data - Fold 4:  50%|███████████████               | 15/30 [00:22<00:21,  1.40s/it]

[[-1.15674867]
 [-1.15674867]
 [-1.15674864]
 [-1.15674888]
 [-1.15674887]
 [-1.15674887]
 [-1.15674889]
 [-1.15674885]
 [-1.15674135]
 [-1.15673297]
 [-1.1567326 ]
 [-1.15673326]
 [-1.15673229]
 [-1.15673272]
 [-1.15673311]
 [-1.15673267]
 [-1.15673276]
 [-1.15673243]
 [-1.15673271]
 [-1.15673321]
 [-1.15672685]
 [-1.15674767]
 [-1.15674769]
 [-1.15674768]]


Forecasting from Training Cold Start Data - Fold 4:  53%|████████████████              | 16/30 [00:23<00:19,  1.37s/it]

[[-1.41362812]
 [-1.4136283 ]
 [-1.41362875]
 [-1.41362838]
 [-1.41362855]
 [-1.41357232]
 [-1.41355483]
 [-1.41355735]
 [-1.4135454 ]
 [-1.41353021]
 [-1.41352612]
 [-1.41352584]
 [-1.41352821]
 [-1.41353473]
 [-1.41353378]
 [-1.41353207]
 [-1.41352316]
 [-1.41352327]
 [-1.41353438]
 [-1.41354416]
 [-1.41354674]
 [-1.41355104]
 [-1.41357127]
 [-1.41357985]]


Forecasting from Training Cold Start Data - Fold 4:  57%|█████████████████             | 17/30 [00:25<00:20,  1.55s/it]

[[-1.19289748]
 [-1.19290214]
 [-1.19290262]
 [-1.1928993 ]
 [-1.19287664]
 [-1.19289839]
 [-1.1928993 ]
 [-1.19290262]
 [-1.19287815]
 [-1.19255499]
 [-1.192616  ]
 [-1.19258066]
 [-1.19247707]
 [-1.19257613]
 [-1.19275523]
 [-1.19276399]
 [-1.19263956]
 [-1.19270842]
 [-1.19273258]
 [-1.19279208]
 [-1.19284161]
 [-1.19289748]
 [-1.19290141]
 [-1.1928996 ]]


Forecasting from Training Cold Start Data - Fold 4:  60%|██████████████████            | 18/30 [00:27<00:19,  1.63s/it]

[[-1.13792561]
 [-1.13792562]
 [-1.13792524]
 [-1.1379257 ]
 [-1.13792583]
 [-1.13792588]
 [-1.13792547]
 [-1.13792536]
 [-1.13787474]
 [-1.13786127]
 [-1.13786593]
 [-1.13786767]
 [-1.13786685]
 [-1.13786748]
 [-1.13786764]
 [-1.13786743]
 [-1.13786715]
 [-1.13786231]
 [-1.13786265]
 [-1.13786294]
 [-1.1378684 ]
 [-1.1379257 ]
 [-1.13792552]
 [-1.13792535]]


Forecasting from Training Cold Start Data - Fold 4:  63%|███████████████████           | 19/30 [00:28<00:17,  1.56s/it]

[[-2.36669384]
 [-2.36669546]
 [-2.3666965 ]
 [-2.36669569]
 [-2.36669446]
 [-2.36669439]
 [-2.36667804]
 [-2.36667637]
 [-2.36667613]
 [-2.36667764]
 [-2.36667895]
 [-2.36668807]
 [-2.36669093]
 [-2.36669166]
 [-2.36669293]
 [-2.36669277]
 [-2.36669239]
 [-2.3666948 ]
 [-2.36669493]
 [-2.36669503]
 [-2.36669567]
 [-2.36669385]
 [-2.3666952 ]
 [-2.36669087]]


Forecasting from Training Cold Start Data - Fold 4:  67%|████████████████████          | 20/30 [00:30<00:14,  1.49s/it]

[[-1.4679555 ]
 [-1.46794961]
 [-1.46795096]
 [-1.46794926]
 [-1.46794865]
 [-1.46794962]
 [-1.46795474]
 [-1.46790231]
 [-1.46789821]
 [-1.46789191]
 [-1.46788911]
 [-1.46788975]
 [-1.46792767]
 [-1.46794202]
 [-1.46792795]
 [-1.46788816]
 [-1.46788516]
 [-1.46788794]
 [-1.46789668]
 [-1.46790892]
 [-1.46794456]
 [-1.4679451 ]
 [-1.46794696]
 [-1.46795287]]


Forecasting from Training Cold Start Data - Fold 4:  70%|█████████████████████         | 21/30 [00:31<00:12,  1.43s/it]

[[-1.2217763 ]
 [-1.2217768 ]
 [-1.22177653]
 [-1.22177685]
 [-1.22177679]
 [-1.22178609]
 [-1.22169108]
 [-1.22173845]
 [-1.22167927]
 [-1.22164376]
 [-1.2216505 ]
 [-1.22165216]
 [-1.2216629 ]
 [-1.22167804]
 [-1.22167888]
 [-1.22166541]
 [-1.22163954]
 [-1.22164064]
 [-1.22164243]
 [-1.2217239 ]
 [-1.2217849 ]
 [-1.22173886]
 [-1.22173982]
 [-1.22174   ]]


Forecasting from Training Cold Start Data - Fold 4:  73%|██████████████████████        | 22/30 [00:32<00:11,  1.40s/it]

[[-2.36364787]
 [-2.363645  ]
 [-2.36364787]
 [-2.36364068]
 [-2.36364643]
 [-2.36364068]
 [-2.36364068]
 [-2.36363205]
 [-2.36362773]
 [-2.36362773]
 [-2.36362485]
 [-2.36362629]
 [-2.36362773]
 [-2.36362917]
 [-2.36362629]
 [-2.36362773]
 [-2.36362773]
 [-2.36363492]
 [-2.36363636]
 [-2.36363924]
 [-2.36364068]
 [-2.3636378 ]
 [-2.36363924]
 [-2.36363924]]


Forecasting from Training Cold Start Data - Fold 4:  77%|███████████████████████       | 23/30 [00:34<00:09,  1.41s/it]

[[-1.7103914 ]
 [-1.71039103]
 [-1.71039107]
 [-1.71039088]
 [-1.71039118]
 [-1.71038632]
 [-1.71038453]
 [-1.71038212]
 [-1.71038168]
 [-1.7103788 ]
 [-1.71037761]
 [-1.71038084]
 [-1.71037912]
 [-1.71037918]
 [-1.71038174]
 [-1.71038338]
 [-1.71038427]
 [-1.71038921]
 [-1.71038974]
 [-1.71039057]
 [-1.7103898 ]
 [-1.71038969]
 [-1.71039059]
 [-1.71039102]]


Forecasting from Training Cold Start Data - Fold 4:  80%|████████████████████████      | 24/30 [00:35<00:08,  1.41s/it]

[[-1.66529984]
 [-1.66530037]
 [-1.66530211]
 [-1.66530037]
 [-1.66530056]
 [-1.66529423]
 [-1.66528913]
 [-1.6652847 ]
 [-1.66527567]
 [-1.66527988]
 [-1.66528185]
 [-1.66527933]
 [-1.66527905]
 [-1.66527909]
 [-1.66528194]
 [-1.66527936]
 [-1.66527782]
 [-1.6652797 ]
 [-1.66527953]
 [-1.66528185]
 [-1.66528353]
 [-1.66529827]
 [-1.66529908]
 [-1.66530072]]


Forecasting from Training Cold Start Data - Fold 4:  83%|█████████████████████████     | 25/30 [00:37<00:07,  1.45s/it]

[[-2.21117648]
 [-2.2111774 ]
 [-2.21117701]
 [-2.21117842]
 [-2.21117697]
 [-2.21117612]
 [-2.21116579]
 [-2.21116358]
 [-2.21116108]
 [-2.21116025]
 [-2.21116424]
 [-2.211165  ]
 [-2.21116141]
 [-2.21116614]
 [-2.21116884]
 [-2.21116994]
 [-2.21116967]
 [-2.21117241]
 [-2.21117393]
 [-2.21117534]
 [-2.21117517]
 [-2.21117488]
 [-2.21117613]
 [-2.21117718]]


Forecasting from Training Cold Start Data - Fold 4:  87%|██████████████████████████    | 26/30 [00:38<00:05,  1.41s/it]

[[-1.45661931]
 [-1.45661979]
 [-1.4566215 ]
 [-1.45662223]
 [-1.45662241]
 [-1.45662258]
 [-1.45662066]
 [-1.45662045]
 [-1.4566187 ]
 [-1.45661791]
 [-1.45661795]
 [-1.45661775]
 [-1.45661859]
 [-1.4566187 ]
 [-1.45661819]
 [-1.45661802]
 [-1.45661842]
 [-1.4566186 ]
 [-1.45661853]
 [-1.45661822]
 [-1.4566176 ]
 [-1.45661772]
 [-1.45661859]
 [-1.45661904]]


Forecasting from Training Cold Start Data - Fold 4:  90%|███████████████████████████   | 27/30 [00:39<00:04,  1.39s/it]

[[-2.29441874]
 [-2.29442089]
 [-2.29442104]
 [-2.29442108]
 [-2.29442082]
 [-2.2944219 ]
 [-2.29442277]
 [-2.29442244]
 [-2.294422  ]
 [-2.29442006]
 [-2.29441793]
 [-2.29441554]
 [-2.2944174 ]
 [-2.29441768]
 [-2.29441814]
 [-2.29441935]
 [-2.29441887]
 [-2.29441758]
 [-2.29441755]
 [-2.29441816]
 [-2.29441871]
 [-2.29441797]
 [-2.29441789]
 [-2.2944205 ]]


Forecasting from Training Cold Start Data - Fold 4:  93%|████████████████████████████  | 28/30 [00:42<00:03,  1.69s/it]

[[-1.6625403 ]
 [-1.66253996]
 [-1.66253984]
 [-1.66254018]
 [-1.66254046]
 [-1.66254051]
 [-1.66252563]
 [-1.66251873]
 [-1.66251606]
 [-1.66251367]
 [-1.66251913]
 [-1.66252236]
 [-1.66252276]
 [-1.66252412]
 [-1.66252392]
 [-1.66252279]
 [-1.6625223 ]
 [-1.66252015]
 [-1.6625192 ]
 [-1.66251865]
 [-1.66252487]
 [-1.66253747]
 [-1.66253677]
 [-1.66253746]]


Forecasting from Training Cold Start Data - Fold 4:  97%|█████████████████████████████ | 29/30 [00:43<00:01,  1.68s/it]

[[-1.11793811]
 [-1.11794403]
 [-1.11794382]
 [-1.11794458]
 [-1.11794428]
 [-1.11794445]
 [-1.11794441]
 [-1.11794437]
 [-1.11794093]
 [-1.1179191 ]
 [-1.11792074]
 [-1.1179217 ]
 [-1.11792086]
 [-1.11792145]
 [-1.11791994]
 [-1.11791851]
 [-1.11792015]
 [-1.11788431]
 [-1.11789497]
 [-1.11785232]
 [-1.1178449 ]
 [-1.11792124]
 [-1.11793417]
 [-1.11793396]]


Forecasting from Training Cold Start Data - Fold 4: 100%|██████████████████████████████| 30/30 [00:45<00:00,  1.59s/it]


In [50]:
a = np.array([np.random.random() for i in range(24)])
av = np.vstack([a,a+0.5])
print(av,av.shape)

[[ 0.69526687  0.45343108  0.15580382  0.38386193  0.7107313   0.38781565
   0.84662046  0.81854201  0.77314714  0.93830505  0.46006457  0.08628216
   0.043596    0.68453984  0.41614401  0.17837524  0.38305887  0.26613085
   0.29869747  0.90025491  0.87572807  0.49391544  0.66586234  0.6130743 ]
 [ 1.19526687  0.95343108  0.65580382  0.88386193  1.2107313   0.88781565
   1.34662046  1.31854201  1.27314714  1.43830505  0.96006457  0.58628216
   0.543596    1.18453984  0.91614401  0.67837524  0.88305887  0.76613085
   0.79869747  1.40025491  1.37572807  0.99391544  1.16586234  1.1130743 ]] (2, 24)


In [57]:
av=np.array([av])
print(av.shape)

(1, 2, 24)


In [66]:
model.predict(av, batch_size=1)

array([[ 0.3579101]], dtype=float32)

# Model 2

https://stackoverflow.com/questions/51720236/multi-feature-sequence-padding-and-masking-in-rnn-using-keras

https://datascience.stackexchange.com/questions/26366/training-an-rnn-with-examples-of-different-lengths-in-keras